services:
  - type: web
    name: tuit-olympiad
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
